### ISSUE TITLE
sqlite3.OperationalError: Could not decode to UTF-8 column 'content' with

### ISSUE THREAD

**Issue by Knight1** [the-paperless-project/paperless#544]
I downloaded https://offenegesetze.de/daten to index it. After hours of scanning I am greeted with this error message. Any ideas?

Thanks

```webserver_1  | Internal Server Error: /admin/documents/document/
webserver_1  | sqlite3.OperationalError: Could not decode to UTF-8 column 'content' with text '     Bundesgesetzblatt
webserver_1  |                                                                                                                          
webserver_1  | 
webserver_1  | The above exception was the direct cause of the following exception:
webserver_1  | 
webserver_1  | Traceback (most recent call last):
webserver_1  |   File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
webserver_1  |     response = get_response(request)
webserver_1  |   File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
webserver_1  |     response = self.process_exception_by_middleware(e, request)
webserver_1  |   File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
webserver_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
webserver_1  |   File "/usr/lib/python3.6/site-packages/django/contrib/admin/options.py", line 575, in wrapper
webserver_1  |     return self.admin_site.admin_view(view)(*args, **kwargs)
webserver_1  |   File "/usr/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
webserver_1  |     response = view_func(request, *args, **kwargs)
webserver_1  |   File "/usr/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
webserver_1  |     response = view_func(request, *args, **kwargs)
webserver_1  |   File "/usr/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 223, in inner
webserver_1  |     return view(request, *args, **kwargs)
webserver_1  |   File "/usr/src/paperless/src/documents/admin.py", line 219, in changelist_view
webserver_1  |     self.document_queue = [doc.id for doc in cl.queryset]
webserver_1  |   File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 272, in __iter__
webserver_1  |     self._fetch_all()
webserver_1  |   File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 1182, in _fetch_all
webserver_1  |     self._result_cache = list(self._iterable_class(self))
webserver_1  |   File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
webserver_1  |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
webserver_1  |   File "/usr/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1101, in execute_sql
webserver_1  |     return list(result)
webserver_1  |   File "/usr/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1462, in cursor_iter
webserver_1  |     for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
webserver_1  |   File "/usr/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1462, in <lambda>
webserver_1  |     for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
webserver_1  |   File "/usr/lib/python3.6/site-packages/django/db/utils.py", line 96, in inner
webserver_1  |     return func(*args, **kwargs)
webserver_1  |   File "/usr/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 33, in <lambda>
webserver_1  |     return lambda s: conv_func(s.decode())
webserver_1  | SystemError: <built-in method decode of bytes object at 0x7f4d09921f10> returned a result with an error set```

**Comment by iamtpage** [comment]
Sounds like the data you indexed contains non UTF-8 characters (accent marks or something from it being in German?)
`Could not decode to UTF-8 column 'content' with text '     Bundesgesetzblatt`

And when it tries to decode it, it fails: `conv_func(s.decode())`
```
webserver_1  |   File "/usr/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 33, in <lambda>
webserver_1  |     return lambda s: conv_func(s.decode())
webserver_1  | SystemError: <built-in method decode of bytes object at 0x7f4d09921f10> returned a result with an error set
```
I'd open up your sqlite database and look at column `content` and see if anything looks wonky
