### ISSUE TITLE
docker-compose.yml Example 

### ISSUE THREAD

**Issue by HeinerDD** [the-paperless-project/paperless#604]
Hi,

it seems the setup with docker was correct, the frontend is running,but the consumer won't work. I put some files into the consumer directory (/media/consume) I have set in docker-compose.yml, but nothing happens.

Is there an example file I can take a look at?

Heiner

**Comment by Tooa** [comment]
Is your consume directory an NFS share? Then [this](https://github.com/the-paperless-project/paperless/issues/482) might solve your problem. Otherwise, can you please post your docker-compose logs of the consumer service after putting a file in the directory?

**Comment by HeinerDD** [comment]
No, its a Samba share on Raspbian. I will try to find the logfile tonight.

**Comment by Tooa** [comment]
Try `docker-compose logs` in the working directory containing your `yml` file.

**Comment by HeinerDD** [comment]
There are no log-files:

![Zwischenablage01](https://user-images.githubusercontent.com/28710143/73469752-26dec100-4387-11ea-930c-f23819eb2cd1.gif)

**Comment by HeinerDD** [comment]
This is the docker-compose.yml:

version: '2.1'

services:
    webserver:
        build: ./
        # uncomment the following line to start automatically on system boot
        restart: always
        ports:
            # You can adapt the port you want Paperless to listen on by
            # modifying the part before the `:`.
            - "8000:8000"
        healthcheck:
            test: ["CMD", "curl" , "-f", "http://localhost:8000"]
            interval: 30s
            timeout: 10s
            retries: 5
        volumes:
            - data:/usr/src/paperless/data
            - media:/usr/src/paperless/media
            # You have to adapt the local path you want the consumption
            # directory to mount to by modifying the part before the ':'.
            - /media/consume:/consume
        env_file: docker-compose.env
        # The reason the line is here is so that the webserver that doesn't do
        # any text recognition and doesn't have to install unnecessary
        # languages the user might have set in the env-file by overwriting the
        # value with nothing.
        environment:
            - PAPERLESS_OCR_LANGUAGES=DE
        command: ["gunicorn", "-b", "0.0.0.0:8000"]

    consumer:
        build: ./
        # uncomment the following line to start automatically on system boot
        restart: always
        depends_on:
            webserver:
                condition: service_healthy
        volumes:
            - data:/usr/src/paperless/data
            - media:/usr/src/paperless/media
            # This should be set to the same value as the consume directory
            # in the webserver service above.
            - /media/consume:/consume
            # Likewise, you can add a local path to mount a directory for
            # exporting. This is not strictly needed for paperless to
            # function, only if you're exporting your files: uncomment
            # it and fill in a local path if you know you're going to
            # want to export your documents.
            # - /path/to/another/arbitrary/place:/export
        env_file: docker-compose.env
        command: ["document_consumer"]

volumes:
    data:
    media:

**Comment by Tooa** [comment]
**Execute** the command `docker-compose logs` in `~/paperless`. You may want to redirect to a file in order to paste the logs here i.e. `docker-compose logs > logfile`.

**Comment by HeinerDD** [comment]
[logfile.log](https://github.com/the-paperless-project/paperless/files/4135975/logfile.log)

**Comment by bauerj** [comment]
The consumer seems to be working fine. What permssions did you apply to `/media/consume` and the files within?

You can run `ls -la /media/consume` to find out. Also, is it a local file system?

**Comment by HeinerDD** [comment]
pi@raspberrypi:/media $ ls -la /media/consume
insgesamt 8168
drwxrwxrwx 2 root root    4096 Jan 30 20:57 .
drwxr-xr-x 3 root root    4096 Jan 20 23:54 ..
-rwxr--r-- 1 pi   pi    496301 Jan  4 10:38 BRN3C2AF4AF1A2E_20200104_103850_000023.pdf
-rwxr--r-- 1 pi   pi    374554 Jan  4 12:25 BRN3C2AF4AF1A2E_20200104_122511_000027.pdf
-rwxr--r-- 1 pi   pi     70665 Jan  4 12:26 BRN3C2AF4AF1A2E_20200104_122629_000029.pdf
-rwxr--r-- 1 pi   pi    753884 Jan  4 12:36 BRN3C2AF4AF1A2E_20200104_123615_000031.pdf
-rwxr--r-- 1 pi   pi    752997 Jan  4 12:37 BRN3C2AF4AF1A2E_20200104_123733_000033.pdf
-rwxr--r-- 1 pi   pi    445010 Jan  4 12:38 BRN3C2AF4AF1A2E_20200104_123821_000035.pdf
-rwxr--r-- 1 pi   pi     69086 Jan  4 12:39 BRN3C2AF4AF1A2E_20200104_123901_000037.pdf
-rwxr--r-- 1 pi   pi     69003 Jan  4 12:40 BRN3C2AF4AF1A2E_20200104_123957_000039.pdf
-rwxr--r-- 1 pi   pi     81951 Jan  4 20:22 BRN3C2AF4AF1A2E_20200104_202238_000043.pdf
-rwxr--r-- 1 pi   pi     79424 Jan  4 20:23 BRN3C2AF4AF1A2E_20200104_202259_000045.pdf
-rwxr--r-- 1 pi   pi    700495 Jan 10 17:59 BRN3C2AF4AF1A2E_20200110_175951_000047.pdf
-rwxr--r-- 1 pi   pi    863001 Jan 10 18:02 BRN3C2AF4AF1A2E_20200110_180154_000049.pdf
-rwxr--r-- 1 pi   pi    282821 Jan 10 18:06 BRN3C2AF4AF1A2E_20200110_180607_000051.pdf

**Comment by HeinerDD** [comment]
Its a local directory on the Pi

**Comment by bauerj** [comment]
Okay, this looks correct too. Please try the following on your Raspberry Pi:

1. Run `docker ps` and see if the consumer is up.
2. If so, run `docker exec -it paperless_consumer_1 ls /consume/`. Does it show any files?
4. If so, run `docker exec -it paperless_consumer_1 python3 /usr/src/paperless/src/manage.py document_consumer` and post the output here.

**Comment by HeinerDD** [comment]
pi@raspberrypi:/ $ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                PORTS                    NAMES
8a4e30badd28        4aae70111499        "/sbin/docker-entryp…"   5 weeks ago         Up 4 days                                      paperless_consumer_1
1d5e009eb9ce        4aae70111499        "/sbin/docker-entryp…"   5 weeks ago         Up 4 days (healthy)   0.0.0.0:8000->8000/tcp   paperless_webserver_1

**Comment by HeinerDD** [comment]
docker exec -it paperless_consumer_1 ls /consume/

No files are shown.

**Comment by HeinerDD** [comment]
docker exec -it paperless_consumer_1 python3 /usr/src/paperless/src/manage.py document_consumer

Starting document consumer at /consume with inotify

**Comment by bauerj** [comment]
Okay, it looks like your directory is not correctly mounted in the Docker container.
Please post the output of `docker inspect paperless_consumer_1`

**Comment by HeinerDD** [comment]
pi@raspberrypi:~ $ docker inspect paperless_consumer_1
[
    {
        "Id": "8a4e30badd288829cb83a6a09a797460604d0cc7f84620c024e768ee19f10699"                                                                           ,
        "Created": "2020-01-20T23:16:21.832778552Z",
        "Path": "/sbin/docker-entrypoint.sh",
        "Args": [
            "document_consumer"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 897,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2020-02-21T22:16:52.602524094Z",
            "FinishedAt": "2020-02-21T22:16:23.135088084Z"
        },
        "Image": "sha256:4aae70111499c780cc25a95de33c141a50f066a5a9a5f0e5c7dec0d                                                                           9c83db4a8",
        "ResolvConfPath": "/var/lib/docker/containers/8a4e30badd288829cb83a6a09a                                                                           797460604d0cc7f84620c024e768ee19f10699/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/8a4e30badd288829cb83a6a09a79                                                                           7460604d0cc7f84620c024e768ee19f10699/hostname",
        "HostsPath": "/var/lib/docker/containers/8a4e30badd288829cb83a6a09a79746                                                                           0604d0cc7f84620c024e768ee19f10699/hosts",
        "LogPath": "/var/lib/docker/containers/8a4e30badd288829cb83a6a09a7974606                                                                           04d0cc7f84620c024e768ee19f10699/8a4e30badd288829cb83a6a09a797460604d0cc7f84620c0                                                                           24e768ee19f10699-json.log",
        "Name": "/paperless_consumer_1",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "paperless_data:/usr/src/paperless/data:rw",
                "/home/pi/paperless/consume:/media/consume:rw",
                "paperless_media:/usr/src/paperless/media:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "paperless_default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": [],
            "CapAdd": null,
            "CapDrop": null,
            "Capabilities": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/013a8cf82a05649921c4c2a06d                                                                           4d0307238f22e6f6d408a2e5b0cd26eb22c994-init/diff:/var/lib/docker/overlay2/73e95f                                                                           1c89608224aba143321a77ccda66a47b2dc7afc188a328b2f88b6e78f2/diff:/var/lib/docker/                                                                           overlay2/be043647c023929b27e2526e413fa86f33c72e079f312d2a3cffb87b17605c3b/diff:/                                                                           var/lib/docker/overlay2/3b4ba0f4236e7d70a93c0e9cb22fcc5e1121d337a0d6a41969f11f51                                                                           c2713af5/diff:/var/lib/docker/overlay2/116654acbde6146ddadd889c66340a8458c312114                                                                           6566c803d0b254f8947c925/diff:/var/lib/docker/overlay2/61bfa704c171b149816086894a                                                                           a984a3ecaaa1e4d14d3543d91526120847f9f3/diff:/var/lib/docker/overlay2/801c4d3ccd6                                                                           5754d2d01a0ac582a456951da372f57faf017375b7389748bcae6/diff:/var/lib/docker/overl                                                                           ay2/c9400b030adfeb62cbb84a9ef73e3088411b2591e7a5a147fb04b95cb500f723/diff:/var/l                                                                           ib/docker/overlay2/37341ee20e76ce2df23ee270676755026327ce2c6ab36e4b292ec33b4a03c                                                                           ffb/diff:/var/lib/docker/overlay2/eb12934d3b424561c241f831520dbf65d591af7de4bafa                                                                           679fd2ff20f8ad1bbe/diff:/var/lib/docker/overlay2/a17f9cd0a74c37c1635d53f87b4eacf                                                                           41320ed2f0c01d2c914ab344a53ebf2e7/diff",
                "MergedDir": "/var/lib/docker/overlay2/013a8cf82a05649921c4c2a06                                                                           d4d0307238f22e6f6d408a2e5b0cd26eb22c994/merged",
                "UpperDir": "/var/lib/docker/overlay2/013a8cf82a05649921c4c2a06d                                                                           4d0307238f22e6f6d408a2e5b0cd26eb22c994/diff",
                "WorkDir": "/var/lib/docker/overlay2/013a8cf82a05649921c4c2a06d4                                                                           d0307238f22e6f6d408a2e5b0cd26eb22c994/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "volume",
                "Name": "7f129b7c7173ecf2f0983a3b2036656ce9e98e3ffcf7b13f667ff1d                                                                           7625dbcc6",
                "Source": "/var/lib/docker/volumes/7f129b7c7173ecf2f0983a3b20366                                                                           56ce9e98e3ffcf7b13f667ff1d7625dbcc6/_data",
                "Destination": "/export",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/home/pi/paperless/consume",
                "Destination": "/media/consume",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "volume",
                "Name": "paperless_data",
                "Source": "/var/lib/docker/volumes/paperless_data/_data",
                "Destination": "/usr/src/paperless/data",
                "Driver": "local",
                "Mode": "rw",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "paperless_media",
                "Source": "/var/lib/docker/volumes/paperless_media/_data",
                "Destination": "/usr/src/paperless/media",
                "Driver": "local",
                "Mode": "rw",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "146d99dd8f08540c48d4ac1ecd4a2c2fb4355a70ffa80a04b4c3614                                                                           d579798cf",
                "Source": "/var/lib/docker/volumes/146d99dd8f08540c48d4ac1ecd4a2                                                                           c2fb4355a70ffa80a04b4c3614d579798cf/_data",
                "Destination": "/consume",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "8a4e30badd28",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/b                                                                           in",
                "PAPERLESS_EXPORT_DIR=/export",
                "PAPERLESS_CONSUMPTION_DIR=/consume"
            ],
            "Cmd": [
                "document_consumer"
            ],
            "Image": "paperless_consumer",
            "Volumes": {
                "/consume": {},
                "/export": {},
                "/media/consume": {},
                "/usr/src/paperless/data": {},
                "/usr/src/paperless/media": {}
            },
            "WorkingDir": "/usr/src/paperless/src",
            "Entrypoint": [
                "/sbin/docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "c867c3c8db8ff93763ddf4ae2976b                                                                           4d04a194ce6f9a52d0ea7e1c7aa610f4078",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "paperless",
                "com.docker.compose.service": "consumer",
                "com.docker.compose.version": "1.21.0",
                "contributors": "Guy Addadi <addadi@gmail.com>, Pit Kleyersburg                                                                            <pitkley@googlemail.com>,         Sven Fischer <git-dev@linux4tw.de>",
                "maintainer": "The Paperless Project https://github.com/the-pape                                                                           rless-project/paperless"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "fac377d78c0a23779a27eb0bfce59758c3fabff96d405318384174                                                                           01fb57abfa",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/fac377d78c0a",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "paperless_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "8a4e30badd28",
                        "consumer"
                    ],
                    "NetworkID": "06c6016141b241aa260a32c2f907821afef684f6be2560                                                                           18b14d37a04f4b939c",
                    "EndpointID": "e289d6e5ff5c56bad923c2144657ff60161fa49c63783                                                                           c4fa14b1b74032a59f7",
                    "Gateway": "172.18.0.1",
                    "IPAddress": "172.18.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:12:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by bauerj** [comment]
Okay, you're mounting `/home/pi/paperless/consume` to `/media/consume` inside the container, both are wrong.

I'm not sure why that's different from the docker-compose.yml you've shown above. Are you sure you were looking at the right file? Maybe you also forgot to run `docker-compose up` again.

**Comment by HeinerDD** [comment]
pi@raspberrypi:~/paperless $ docker-compose up
Starting paperless_webserver_1 ... done
Recreating paperless_consumer_1 ...
WARNING: Service "consumer" is using volume "/consume" from the previous contain                         er. Host mapping "/media/consume" has no effect. Remove the existing containers                          Recreating paperless_consumer_1 ... done
Attaching to paperless_webserver_1, paperless_consumer_1
webserver_1  | Operations to perform:
webserver_1  |   Apply all migrations: admin, auth, contenttypes, documents, rem                         inders, sessions
webserver_1  | Running migrations:
webserver_1  |   No migrations to apply.
webserver_1  | [2020-02-28 19:59:21 +0000] [1] [INFO] Starting gunicorn 19.9.0
webserver_1  | [2020-02-28 19:59:21 +0000] [1] [INFO] Listening at: http://0.0.0                         .0:8000 (1)
webserver_1  | [2020-02-28 19:59:21 +0000] [1] [INFO] Using worker: sync
webserver_1  | [2020-02-28 19:59:21 +0000] [1] [INFO] Server is ready. Spawning                          workers
webserver_1  | [2020-02-28 19:59:21 +0000] [34] [INFO] Booting worker with pid:                          34
webserver_1  | 127.0.0.1 - - [28/Feb/2020:19:59:46 +0000] "GET / HTTP/1.1" 301 0                          "-" "curl/7.66.0"
consumer_1   | Operations to perform:
consumer_1   |   Apply all migrations: admin, auth, contenttypes, documents, rem                         inders, sessions
consumer_1   | Running migrations:
consumer_1   |   No migrations to apply.
consumer_1   | Starting document consumer at /consume with inotify
webserver_1  | 127.0.0.1 - - [28/Feb/2020:20:00:16 +0000] "GET / HTTP/1.1" 301 0                          "-" "curl/7.66.0"
webserver_1  | 127.0.0.1 - - [28/Feb/2020:20:00:47 +0000] "GET / HTTP/1.1" 301 0 "-" "curl/7.66.0        "
webserver_1  | 127.0.0.1 - - [28/Feb/2020:20:01:17 +0000] "GET / HTTP/1.1" 301 0 "-" "curl/7.66.0        "
webserver_1  | 127.0.0.1 - - [28/Feb/2020:20:01:47 +0000] "GET / HTTP/1.1" 301 0 "-" "curl/7.66.0        "
webserver_1  | 127.0.0.1 - - [28/Feb/2020:20:02:18 +0000] "GET / HTTP/1.1" 301 0 "-" "curl/7.66.0        "
webserver_1  | 127.0.0.1 - - [28/Feb/2020:20:02:48 +0000] "GET / HTTP/1.1" 301 0 "-" "curl/7.66.0        "

**Comment by bauerj** [comment]
Oh, okay. Use ` docker-compose up --force-recreate` then.

**Comment by HeinerDD** [comment]
Did not work:

pi@raspberrypi:~/paperless $ docker-compose up --force-recreate
Recreating paperless_webserver_1 ...
WARNING: Service "webserver" is using volume "/consume" from the previous container. Host mapping "/media/consume" has no effect. Remove the existing containers
Recreating paperless_webserver_1 ... done

**Comment by bauerj** [comment]
Can you try `docker-compose down -v -f` and then start it again?

**Comment by HeinerDD** [comment]
pi@raspberrypi:~/paperless $ docker-compose down -v -f
Stops containers and removes containers, networks, volumes, and images
created by `up`.

By default, the only things removed are:

- Containers for services defined in the Compose file
- Networks defined in the `networks` section of the Compose file
- The default network, if one is used

Networks and volumes defined as `external` are never removed.

Usage: down [options]

Options:
    --rmi type              Remove images. Type must be one of:
                              'all': Remove all images used by any service.
                              'local': Remove only images that don't have a
                              custom tag set by the `image` field.
    -v, --volumes           Remove named volumes declared in the `volumes`
                            section of the Compose file and anonymous volumes
                            attached to containers.
    --remove-orphans        Remove containers for services not defined in the
                            Compose file
    -t, --timeout TIMEOUT   Specify a shutdown timeout in seconds.
                            (default: 10)
pi@raspberrypi:~/paperless $ docker-compose up --force-recreate
Recreating paperless_webserver_1 ...
WARNING: Service "webserver" is using volume "/consume" from the previous container. Host mapping "/media/consume" has no effect. RRecreating paperless_webserver_1 ... done

**Comment by bauerj** [comment]
It should be `docker-compose down -v `

**Comment by HeinerDD** [comment]
Seems that it worked, but I cant creat a superuser now:

pi@raspberrypi:~/paperless $ docker-compose run --rm webserver createsuperuser
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, documents, reminders, sessions
Running migrations:
  No migrations to apply.
Username (leave blank to use 'paperless'):
Email address: **********
Password:
Password (again):
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 305, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 59, in execute
    return super().execute(*args, **options)
  File "/usr/lib/python3.7/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 179, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(**user_data)
  File "/usr/lib/python3.7/site-packages/django/contrib/auth/models.py", line 161, in create_superuser
    return self._create_user(username, email, password, **extra_fields)
  File "/usr/lib/python3.7/site-packages/django/contrib/auth/models.py", line 144, in _create_user
    user.save(using=self._db)
  File "/usr/lib/python3.7/site-packages/django/contrib/auth/base_user.py", line 73, in save
    super().save(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/django/db/models/base.py", line 729, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/lib/python3.7/site-packages/django/db/models/base.py", line 759, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/lib/python3.7/site-packages/django/db/models/base.py", line 842, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/lib/python3.7/site-packages/django/db/models/base.py", line 880, in _do_insert
    using=using, raw=raw)
  File "/usr/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/django/db/models/query.py", line 1128, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1285, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/usr/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 305, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: database is locked

**Comment by bauerj** [comment]
It was probably still importing your files, just try again.
