### ISSUE TITLE
Crash during OCR (running in a container on Synology NAS Docker)

### ISSUE THREAD

**Issue by mikkelnl** [the-paperless-project/paperless#606]
I have a PDF, containing 2 pages made with the 'Notes' app on an iPhone by 'scanning' the document.

Done this before with no problems, but Paperless Consumer is crashing with this document. The log files shows:

`

2020-01-28 15:22:55 | stdout | pyocr.error.TesseractError: (-11, b'Tesseract Open Source OCR Engine v4.0.0 with Leptonica\ncontains_unichar_id(unichar_id):Error:Assert failed:in file ../../src/ccutil/unicharset.h, line 502\n')
-- | -- | --
2020-01-28 15:22:55 | stdout | raise self._value
2020-01-28 15:22:55 | stdout | File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get
2020-01-28 15:22:55 | stdout | return self._map_async(func, iterable, mapstar, chunksize).get()
2020-01-28 15:22:55 | stdout | File "/usr/lib/python3.7/multiprocessing/pool.py", line 268, in map
2020-01-28 15:22:55 | stdout | r = pool.map(image_to_string, itertools.product(imgs, [lang]))
2020-01-28 15:22:55 | stdout | File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 222, in _ocr
2020-01-28 15:22:55 | stdout | raw_text = self._ocr([imgs[middle]], self.DEFAULT_OCR_LANGUAGE)
2020-01-28 15:22:55 | stdout | File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 170, in _get_ocr
2020-01-28 15:22:55 | stdout | self._text = self._get_ocr(images)
2020-01-28 15:22:55 | stdout | File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 110, in get_text
2020-01-28 15:22:55 | stdout | text = self.get_text()
2020-01-28 15:22:55 | stdout | File "/usr/src/paperless/src/documents/parsers.py", line 127, in get_date
2020-01-28 15:22:55 | stdout | date = parsed_document.get_date()
2020-01-28 15:22:55 | stdout | File "/usr/src/paperless/src/documents/consumer.py", line 153, in try_consume_file
2020-01-28 15:22:55 | stdout | return func(*args, **kwds)
2020-01-28 15:22:55 | stdout | File "/usr/lib/python3.7/contextlib.py", line 74, in inner
2020-01-28 15:22:55 | stdout | if not self.try_consume_file(file):
2020-01-28 15:22:55 | stdout | File "/usr/src/paperless/src/documents/consumer.py", line 112, in consume_new_files
2020-01-28 15:22:55 | stdout | self.file_consumer.consume_new_files()
2020-01-28 15:22:55 | stdout | File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 121, in loop_step
2020-01-28 15:22:55 | stdout | self.loop_step(mail_delta)
2020-01-28 15:22:55 | stdout | File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 129, in loop_inotify
2020-01-28 15:22:55 | stdout | self.loop_inotify(mail_delta)
2020-01-28 15:22:55 | stdout | File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 96, in handle
2020-01-28 15:22:55 | stdout | output = self.handle(*args, **options)
2020-01-28 15:22:55 | stdout | File "/usr/lib/python3.7/site-packages/django/core/management/base.py", line 335, in execute
2020-01-28 15:22:55 | stdout | self.execute(*args, **cmd_options)
2020-01-28 15:22:55 | stdout | File "/usr/lib/python3.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
2020-01-28 15:22:55 | stdout | self.fetch_command(subcommand).run_from_argv(self.argv)
2020-01-28 15:22:55 | stdout | File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 365, in execute
2020-01-28 15:22:55 | stdout | utility.execute()
2020-01-28 15:22:55 | stdout | File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
2020-01-28 15:22:55 | stdout | execute_from_command_line(sys.argv)
2020-01-28 15:22:55 | stdout | File "/usr/src/paperless/src/manage.py", line 11, in <module>
2020-01-28 15:22:55 | stdout | Traceback (most recent call last):
2020-01-28 15:22:55 | stdout |  
2020-01-28 15:22:55 | stdout | The above exception was the direct cause of the following exception:
2020-01-28 15:22:55 | stdout |  
2020-01-28 15:22:55 | stdout | """
2020-01-28 15:22:55 | stdout | pyocr.error.TesseractError: (-11, b'Tesseract Open Source OCR Engine v4.0.0 with Leptonica\ncontains_unichar_id(unichar_id):Error:Assert failed:in file ../../src/ccutil/unicharset.h, line 502\n')
2020-01-28 15:22:55 | stdout | raise TesseractError(status, errors)
2020-01-28 15:22:55 | stdout | File "/usr/lib/python3.7/site-packages/pyocr/tesseract.py", line 373, in image_to_string
2020-01-28 15:22:55 | stdout | return ocr.image_to_string(f, lang=lang)
2020-01-28 15:22:55 | stdout | File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 277, in image_to_string
2020-01-28 15:22:55 | stdout | return list(map(*args))
2020-01-28 15:22:55 | stdout | File "/usr/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
2020-01-28 15:22:55 | stdout | result = (True, func(*args, **kwds))
2020-01-28 15:22:55 | stdout | File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
2020-01-28 15:22:55 | stdout | Traceback (most recent call last):
2020-01-28 15:22:55 | stdout | """
2020-01-28 15:22:55 | stdout | multiprocessing.pool.RemoteTraceback:
2020-01-28 15:22:30 | stdout | Parsing for nld
2020-01-28 15:22:30 | stdout | [0mOCRing the document
2020-01-28 15:22:30 | stdout | [0m[1;35m[image2 @ 0x7f571124f600] [0m[0;33mEncoder did not produce proper pts, making some up.
2020-01-28 15:22:30 | stdout | [0m[1;35m[image2 @ 0x7f571124f600] [0m[0;33mUsing AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
2020-01-28 15:22:28 | stdout | [0m[1;35m[image2 @ 0x7f52f8bb9600] [0m[0;33mEncoder did not produce proper pts, making some up.
2020-01-28 15:22:28 | stdout | [0m[1;35m[image2 @ 0x7f52f8bb9600] [0m[0;33mUsing AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
2020-01-28 15:21:56 | stdout | [0m[0;35m[pgm_pipe @ 0x7f571124df80] [0m[0;33mStream #0: not enough frames to estimate rate; consider increasing probesize
2020-01-28 15:21:56 | stdout | [0;35m[pgm_pipe @ 0x7f52f8bb7f80] [0m[0;33mStream #0: not enough frames to estimate rate; consider increasing probesize
2020-01-28 15:21:56 | stdout | Processing sheet #1: /tmp/paperless/paperless-hl64q_vp/convert-0001.pnm -> /tmp/paperless/paperless-hl64q_vp/convert-0001.unpaper.pnm
2020-01-28 15:21:56 | stdout | Processing sheet #1: /tmp/paperless/paperless-hl64q_vp/convert-0000.pnm -> /tmp/paperless/paperless-hl64q_vp/convert-0000.unpaper.pnm
2020-01-28 15:21:40 | stdout |  
2020-01-28 15:21:40 | stdout | Output file size = 919004 bytes (34914 bytes = 3.66% decrease)
2020-01-28 15:21:40 | stdout | Output IDAT size = 918947 bytes (34566 bytes decrease)
2020-01-28 15:21:40 | stdout |  
2020-01-28 15:21:39 | stdout | Output file: /tmp/paperless/paperless-hl64q_vp/optipng.png
2020-01-28 15:21:39 | stdout |  
2020-01-28 15:21:39 | stdout | zc = 9  zm = 8  zs = 0  f = 0 IDAT size = 918947
2020-01-28 15:21:39 | stdout | Selecting parameters:
2020-01-28 15:21:39 | stdout | zc = 9  zm = 9  zs = 1  f = 0   zc = 9  zm = 8  zs = 1  f = 0   zc = 1  zm = 9  zs = 2  f = 0   zc = 1  zm = 8  zs = 2  f = 0   zc = 9  zm = 9  zs = 3  f = 0   zc = 9  zm = 8  zs = 3  f = 0   zc = 9  zm = 9  zs = 0  f = 1   zc = 9  zm = 8  zs = 0  f = 1   zc = 9  zm = 9  zs = 1  f = 1   zc = 9  zm = 8  zs = 1  f = 1   zc = 1  zm = 9  zs = 2  f = 1   zc = 1  zm = 8  zs = 2  f = 1   zc = 9  zm = 9  zs = 3  f = 1   zc = 9  zm = 8  zs = 3  f = 1   zc = 9  zm = 9  zs = 0  f = 2   zc = 9  zm = 8  zs = 0  f = 2   zc = 9  zm = 9  zs = 1  f = 2   zc = 9  zm = 8  zs = 1  f = 2   zc = 1  zm = 9  zs = 2  f = 2   zc = 1  zm = 8  zs = 2  f = 2   zc = 9  zm = 9  zs = 3  f = 2   zc = 9  zm = 8  zs = 3  f = 2   zc = 9  zm = 9  zs = 0  f = 3   zc = 9  zm = 8  zs = 0  f = 3   zc = 9  zm = 9  zs = 1  f = 3   zc = 9  zm = 8  zs = 1  f = 3   zc = 1  zm = 9  zs = 2  f = 3   zc = 1  zm = 8  zs = 2  f = 3   zc = 9  zm = 9  zs = 3  f = 3   zc = 9  zm = 8  zs = 3  f = 3   zc = 9  zm = 9  zs = 0  f = 4   zc = 9  zm = 8  zs = 0  f = 4   zc = 9  zm = 9  zs = 1  f = 4   zc = 9  zm = 8  zs = 1  f = 4   zc = 1  zm = 9  zs = 2  f = 4   zc = 1  zm = 8  zs = 2  f = 4   zc = 9  zm = 9  zs = 3  f = 4   zc = 9  zm = 8  zs = 3  f = 4   zc = 9  zm = 9  zs = 0  f = 5   zc = 9  zm = 8  zs = 0  f = 5   zc = 9  zm = 9  zs = 1  f = 5   zc = 9  zm = 8  zs = 1  f = 5   zc = 1  zm = 9  zs = 2  f = 5   zc = 1  zm = 8  zs = 2  f = 5   zc = 9  zm = 9  zs = 3  f = 5   zc = 9  zm = 8  zs = 3  f = 5
2020-01-28 15:21:12 | stdout | zc = 9  zm = 8  zs = 0  f = 0 IDAT size = 918947
2020-01-28 15:21:12 | stdout | zc = 9  zm = 9  zs = 0  f = 0 IDAT size = 919285
2020-01-28 15:21:11 | stdout | Trying:
2020-01-28 15:21:11 | stdout |  
2020-01-28 15:21:11 | stdout | Input file size = 953918 bytes
2020-01-28 15:21:11 | stdout | Input IDAT size = 953513 bytes
2020-01-28 15:21:11 | stdout | 422x595 pixels, 3x16 bits/pixel, RGB
2020-01-28 15:21:11 | stdout | ** Processing: /tmp/paperless/paperless-hl64q_vp/convert.png

`

Any ideas what might cause this?

**Comment by goose-ws** [comment]
I'm having a similar issue, which it seems is the root of #602 -- With OCR continually failing then retrying, it creates a new directory each time, without cleaning up the old one.

Anyways, I'm using Paperless via Docker on Debian Stable x64. My relevant logs are the same:

```
2020-01-31T18:09:43.650442791Z Consuming /consume/2020-01-13 16:20:03.pdf


2020-01-31T18:09:44.102860998Z ** Processing: /tmp/paperless/paperless-u6qewmuu/convert.png


2020-01-31T18:09:44.123916080Z 500x669 pixels, 3x16 bits/pixel, RGB


2020-01-31T18:09:44.123936039Z Input IDAT size = 1052816 bytes


2020-01-31T18:09:44.123943032Z Input file size = 1053257 bytes


2020-01-31T18:09:44.123949018Z 


2020-01-31T18:09:44.123954737Z Trying:


2020-01-31T18:09:44.585987733Z   zc = 9  zm = 9  zs = 0  f = 0		IDAT size = 1023303


2020-01-31T18:10:01.499574197Z   zc = 9  zm = 8  zs = 0  f = 0
  zc = 9  zm = 9  zs = 1  f = 0
  zc = 9  zm = 8  zs = 1  f = 0
  zc = 1  zm = 9  zs = 2  f = 0
  zc = 1  zm = 8  zs = 2  f = 0
  zc = 9  zm = 9  zs = 3  f = 0
  zc = 9  zm = 8  zs = 3  f = 0
  zc = 9  zm = 9  zs = 0  f = 1
  zc = 9  zm = 8  zs = 0  f = 1
  zc = 9  zm = 9  zs = 1  f = 1
  zc = 9  zm = 8  zs = 1  f = 1
  zc = 1  zm = 9  zs = 2  f = 1
  zc = 1  zm = 8  zs = 2  f = 1
  zc = 9  zm = 9  zs = 3  f = 1
  zc = 9  zm = 8  zs = 3  f = 1
  zc = 9  zm = 9  zs = 0  f = 2
  zc = 9  zm = 8  zs = 0  f = 2
  zc = 9  zm = 9  zs = 1  f = 2
  zc = 9  zm = 8  zs = 1  f = 2
  zc = 1  zm = 9  zs = 2  f = 2
  zc = 1  zm = 8  zs = 2  f = 2
  zc = 9  zm = 9  zs = 3  f = 2
  zc = 9  zm = 8  zs = 3  f = 2
  zc = 9  zm = 9  zs = 0  f = 3
  zc = 9  zm = 8  zs = 0  f = 3
  zc = 9  zm = 9  zs = 1  f = 3
  zc = 9  zm = 8  zs = 1  f = 3
  zc = 1  zm = 9  zs = 2  f = 3
  zc = 1  zm = 8  zs = 2  f = 3
  zc = 9  zm = 9  zs = 3  f = 3
  zc = 9  zm = 8  zs = 3  f = 3
  zc = 9  zm = 9  zs = 0  f = 4
  zc = 9  zm = 8  zs = 0  f = 4
  zc = 9  zm = 9  zs = 1  f = 4
  zc = 9  zm = 8  zs = 1  f = 4
  zc = 1  zm = 9  zs = 2  f = 4
  zc = 1  zm = 8  zs = 2  f = 4
  zc = 9  zm = 9  zs = 3  f = 4
  zc = 9  zm = 8  zs = 3  f = 4
  zc = 9  zm = 9  zs = 0  f = 5
  zc = 9  zm = 8  zs = 0  f = 5
  zc = 9  zm = 9  zs = 1  f = 5
  zc = 9  zm = 8  zs = 1  f = 5
  zc = 1  zm = 9  zs = 2  f = 5
  zc = 1  zm = 8  zs = 2  f = 5
  zc = 9  zm = 9  zs = 3  f = 5
  zc = 9  zm = 8  zs = 3  f = 5
                               


2020-01-31T18:10:01.499624090Z Selecting parameters:


2020-01-31T18:10:01.499628467Z   zc = 9  zm = 9  zs = 0  f = 0		IDAT size = 1023303


2020-01-31T18:10:01.499632610Z 


2020-01-31T18:10:01.499636027Z Output file: /tmp/paperless/paperless-u6qewmuu/optipng.png


2020-01-31T18:10:01.961654033Z 


2020-01-31T18:10:01.961674107Z Output IDAT size = 1023303 bytes (29513 bytes decrease)


2020-01-31T18:10:01.961680336Z Output file size = 1023360 bytes (29897 bytes = 2.84% decrease)


2020-01-31T18:10:01.961824583Z 


2020-01-31T18:10:04.893549682Z Processing sheet #1: /tmp/paperless/paperless-u6qewmuu/convert-0000.pnm -> /tmp/paperless/paperless-u6qewmuu/convert-0000.unpaper.pnm


2020-01-31T18:10:04.903046571Z [pgm_pipe @ 0x564f78ef6f80] Stream #0: not enough frames to estimate rate; consider increasing probesize


2020-01-31T18:10:13.845031837Z [image2 @ 0x564f78ef8600] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.


2020-01-31T18:10:13.852445451Z [image2 @ 0x564f78ef8600] Encoder did not produce proper pts, making some up.


2020-01-31T18:10:13.906280822Z OCRing the document


2020-01-31T18:10:13.907747064Z Parsing for eng


2020-01-31T18:10:20.947474099Z multiprocessing.pool.RemoteTraceback: 


2020-01-31T18:10:20.947520715Z """


2020-01-31T18:10:20.947527594Z Traceback (most recent call last):


2020-01-31T18:10:20.947533299Z   File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker


2020-01-31T18:10:20.947539131Z     result = (True, func(*args, **kwds))


2020-01-31T18:10:20.947544717Z   File "/usr/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar


2020-01-31T18:10:20.947550314Z     return list(map(*args))


2020-01-31T18:10:20.947555469Z   File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 277, in image_to_string


2020-01-31T18:10:20.947561202Z     return ocr.image_to_string(f, lang=lang)


2020-01-31T18:10:20.947566447Z   File "/usr/lib/python3.7/site-packages/pyocr/tesseract.py", line 373, in image_to_string


2020-01-31T18:10:20.947572138Z     raise TesseractError(status, errors)


2020-01-31T18:10:20.947577551Z pyocr.error.TesseractError: (-11, b'Tesseract Open Source OCR Engine v4.0.0 with Leptonica\ncontains_unichar_id(unichar_id):Error:Assert failed:in file ../../src/ccutil/unicharset.h, line 502\n')


2020-01-31T18:10:20.947583760Z """


2020-01-31T18:10:20.947588853Z 


2020-01-31T18:10:20.947593796Z The above exception was the direct cause of the following exception:


2020-01-31T18:10:20.947599228Z 


2020-01-31T18:10:20.947604051Z Traceback (most recent call last):


2020-01-31T18:10:20.947609166Z   File "/usr/src/paperless/src/manage.py", line 11, in <module>


2020-01-31T18:10:20.947615058Z     execute_from_command_line(sys.argv)


2020-01-31T18:10:20.947620457Z   File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line


2020-01-31T18:10:20.947626218Z     utility.execute()


2020-01-31T18:10:20.947631295Z   File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 365, in execute


2020-01-31T18:10:20.947636921Z     self.fetch_command(subcommand).run_from_argv(self.argv)


2020-01-31T18:10:20.947642044Z   File "/usr/lib/python3.7/site-packages/django/core/management/base.py", line 288, in run_from_argv


2020-01-31T18:10:20.947647589Z     self.execute(*args, **cmd_options)


2020-01-31T18:10:20.947652826Z   File "/usr/lib/python3.7/site-packages/django/core/management/base.py", line 335, in execute


2020-01-31T18:10:20.947658227Z     output = self.handle(*args, **options)


2020-01-31T18:10:20.947663413Z   File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 97, in handle


2020-01-31T18:10:20.947668859Z     self.loop_inotify(mail_delta)


2020-01-31T18:10:20.947673857Z   File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 130, in loop_inotify


2020-01-31T18:10:20.947692746Z     self.loop_step(mail_delta)


2020-01-31T18:10:20.947698720Z   File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 122, in loop_step


2020-01-31T18:10:20.947704441Z     self.file_consumer.consume_new_files()


2020-01-31T18:10:20.947711001Z   File "/usr/src/paperless/src/documents/consumer.py", line 117, in consume_new_files


2020-01-31T18:10:20.947716921Z     if not self.try_consume_file(file):


2020-01-31T18:10:20.947722154Z   File "/usr/lib/python3.7/contextlib.py", line 74, in inner


2020-01-31T18:10:20.947727493Z     return func(*args, **kwds)


2020-01-31T18:10:20.947732735Z   File "/usr/src/paperless/src/documents/consumer.py", line 158, in try_consume_file


2020-01-31T18:10:20.947738447Z     date = parsed_document.get_date()


2020-01-31T18:10:20.947743557Z   File "/usr/src/paperless/src/documents/parsers.py", line 127, in get_date


2020-01-31T18:10:20.947749192Z     text = self.get_text()


2020-01-31T18:10:20.947754335Z   File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 110, in get_text


2020-01-31T18:10:20.947759871Z     self._text = self._get_ocr(images)


2020-01-31T18:10:20.947764943Z   File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 170, in _get_ocr


2020-01-31T18:10:20.947770453Z     raw_text = self._ocr([imgs[middle]], self.DEFAULT_OCR_LANGUAGE)


2020-01-31T18:10:20.947775690Z   File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 222, in _ocr


2020-01-31T18:10:20.947781039Z     r = pool.map(image_to_string, itertools.product(imgs, [lang]))


2020-01-31T18:10:20.947786270Z   File "/usr/lib/python3.7/multiprocessing/pool.py", line 268, in map


2020-01-31T18:10:20.947791688Z     return self._map_async(func, iterable, mapstar, chunksize).get()


2020-01-31T18:10:20.947796887Z   File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get


2020-01-31T18:10:20.947802173Z     raise self._value


2020-01-31T18:10:20.947807423Z pyocr.error.TesseractError: (-11, b'Tesseract Open Source OCR Engine v4.0.0 with Leptonica\ncontains_unichar_id(unichar_id):Error:Assert failed:in file ../../src/ccutil/unicharset.h, line 502\n')


2020-01-31T18:10:23.138880477Z Starting document consumer at /consume with inotify


2020-01-31T18:10:23.649822246Z Parsers available: RasterisedDocumentParser


2020-01-31T18:10:23.651063155Z Consuming /consume/2020-01-13 16:20:03.pdf
```
