### ISSUE TITLE
manage.py errors

### ISSUE THREAD

**Issue by russdyer** [the-paperless-project/paperless#608]
doing a bare metal install and getting the following every time I run a ./manage.py command:

Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/home/username/virtualenvironment/paperless/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/username/virtualenvironment/paperless/lib/python3.6/site-packages/django/core/management/__init__.py", line 317, in execute
    settings.INSTALLED_APPS
  File "/home/username/virtualenvironment/paperless/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/username/virtualenvironment/paperless/lib/python3.6/site-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/username/virtualenvironment/paperless/lib/python3.6/site-packages/django/conf/__init__.py", line 106, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/username/virtualenvironment/paperless/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/share/paperless/src/paperless/settings.py", line 17, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

**Comment by bauerj** [comment]
Hey,

it seems to me you did not install the Python requirements. Can you try running `pip install  --requirement /path/to/paperless/requirements.txt` to see if that fixes the issue?
