### ISSUE TITLE
Database is locked error in consumer

### ISSUE THREAD

**Issue by zawnk** [the-paperless-project/paperless#616]
I have paperless running in a docker container on my RPi4. I've mounted my NAS and mapped the folders for export and consume to some NAS folders which works just fine. Now I wanted to change the storage of the /data and /media folders also to the NAS because I trust my RAID setup much more than the SD card in my RPi4. So I've changed the volumes for /media and /data in the .env file:

```
version: '2.1'

services:
    webserver:
        build: ./
        # uncomment the following line to start automatically on system boot
        # restart: always
        ports:
            # You can adapt the port you want Paperless to listen on by
            # modifying the part before the `:`.
            - "8585:8000"
        healthcheck:
            test: ["CMD", "curl" , "-f", "http://localhost:8000"]
            interval: 30s
            timeout: 10s
            retries: 5
        volumes:
            - data2:/usr/src/paperless/data
            - media2:/usr/src/paperless/media
            # You have to adapt the local path you want the consumption
            # directory to mount to by modifying the part before the ':'.
            - /media/nas/Documents/consume:/consume
        env_file: docker-compose.env
        # The reason the line is here is so that the webserver that doesn't do
        # any text recognition and doesn't have to install unnecessary
        # languages the user might have set in the env-file by overwriting the
        # value with nothing.
        environment:
            - PAPERLESS_OCR_LANGUAGES=eng deu
        command: ["gunicorn", "-b", "0.0.0.0:8000"]

    consumer:
        build: ./
        # uncomment the following line to start automatically on system boot
        # restart: always
        depends_on:
            webserver:
                condition: service_healthy
        volumes:
            - data2:/usr/src/paperless/data
            - media2:/usr/src/paperless/media
            # This should be set to the same value as the consume directory
            # in the webserver service above.
            - /media/nas/Documents/consume:/consume
            # Likewise, you can add a local path to mount a directory for
            # exporting. This is not strictly needed for paperless to
            # function, only if you're exporting your files: uncomment
            # it and fill in a local path if you know you're going to
            # want to export your documents.
            # - /path/to/another/arbitrary/place:/export
            - /media/nas/Documents/paperless/export:/export
        env_file: docker-compose.env
        command: ["document_consumer", "--no-inotify"]

volumes:
    data2:
        driver: local
        driver_opts:
             type: 'none'
             o: 'bind'
             device: '/media/nas/Documents/paperless/data'
    media2:
        driver: local
        driver_opts:
             type: 'none'
             o: 'bind'
             device: '/media/nas/Documents/paperless/media'
```
I copied the existing data into the corresponding folders, after it didn't work without any files in the folders (same error). As soon as a file is supposed to be imported, i get the 'database is locked' error.

```
paperless git:(master) sudo docker logs -f paperless_consumer_1
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, documents, reminders, sessions
Running migrations:
  No migrations to apply.
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/armv7/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/armv7/APKINDEX.tar.gz
(1/1) Installing tesseract-ocr-data-deu (4.0.0-r2)
OK: 257 MiB in 126 packages
Starting document consumer at /consume
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/django/db/backends/base/base.py", line 239, in _commit
    return self.connection.commit()
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.7/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 88, in handle
    " with inotify" if use_inotify else ""
  File "/usr/lib/python3.7/logging/__init__.py", line 1378, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 1524, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 894, in handle
    self.emit(record)
  File "/usr/src/paperless/src/documents/loggers.py", line 23, in emit
    Log.objects.create(**kwargs)
  File "/usr/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/django/db/models/query.py", line 417, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/src/paperless/src/documents/models.py", line 353, in save
    models.Model.save(self, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/django/db/models/base.py", line 729, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/lib/python3.7/site-packages/django/db/models/base.py", line 759, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/lib/python3.7/site-packages/django/db/transaction.py", line 212, in __exit__
    connection.commit()
  File "/usr/lib/python3.7/site-packages/django/db/backends/base/base.py", line 261, in commit
    self._commit()
  File "/usr/lib/python3.7/site-packages/django/db/backends/base/base.py", line 239, in _commit
    return self.connection.commit()
  File "/usr/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/lib/python3.7/site-packages/django/db/backends/base/base.py", line 239, in _commit
    return self.connection.commit()
django.db.utils.OperationalError: database is locked
```

So any idea what is causing the sqlite file to be locked? I don't have it open or anything as far as I'm aware. Any help or tips to tackle the problem would be appreciated :)

**Comment by MasterofJOKers** [comment]
Can you still open it manually or is it locked there, too?

**Comment by zawnk** [comment]
Just tried it, same issues. If I start it without copying /media and /data before, the container can't even be built. If I copy the files, it works and starts fine, until briefly after the start the same error occurs.

That said, when I open the sqlite file with sqlitebrowser from my Windows machine, reading and writing works just fine. When I open the sqlite file from the RPi with sqlitebrowser reading works fine, but when I want to commit changes, I also get "database is locked" errors. Any idea why the database reports locked in one case and not in the other? Anything I can try?
