### ISSUE TITLE
Consumer crashes with value error

### ISSUE THREAD

**Issue by languitar** [the-paperless-project/paperless#620]
```
consumer_1   | 2020-03-08T16:49:28.163248689Z Starting document consumer at /consume with inotify
consumer_1   | 2020-03-08T16:49:28.936251454Z Parsers available: RasterisedDocumentParser
consumer_1   | 2020-03-08T16:49:28.938736146Z Consuming /consume/20110411Z - LBV - Meldebescheinigung.pdf
consumer_1   | 2020-03-08T16:49:30.088413646Z ** Processing: /tmp/paperless/paperless-5d25bzsx/convert.png
consumer_1   | 2020-03-08T16:49:30.101952506Z 500x700 pixels, 16 bits/pixel, grayscale
consumer_1   | 2020-03-08T16:49:30.102106910Z Input IDAT size = 137588 bytes
consumer_1   | 2020-03-08T16:49:30.102169324Z Input file size = 137693 bytes
consumer_1   | 2020-03-08T16:49:30.102227563Z 
consumer_1   | 2020-03-08T16:49:30.102285477Z Trying:
consumer_1   | 2020-03-08T16:49:30.255749348Z   zc = 9  zm = 9  zs = 0  f = 0		IDAT size = 133550
  zc = 9  zm = 9  zs = 1  f = 0:30.56260IDAT size = 132352 = 8  zs = 0  f = 0
  zc = 9  zm = 9  zs = 3  f = 0:31.28693IDAT size = 131966 = 8  zs = 1  f = 0
                               :37.757163857Z   zc = 9  zm = 8  zs = 3  f = 0
consumer_1   | 2020-03-08T16:49:37.757317473Z Selecting parameters:
consumer_1   | 2020-03-08T16:49:37.757339474Z   zc = 9  zm = 9  zs = 3  f = 0		IDAT size = 131966
consumer_1   | 2020-03-08T16:49:37.757361274Z 
consumer_1   | 2020-03-08T16:49:37.757380775Z Output file: /tmp/paperless/paperless-5d25bzsx/optipng.png
consumer_1   | 2020-03-08T16:49:38.020932849Z 
consumer_1   | 2020-03-08T16:49:38.021043564Z Output IDAT size = 131966 bytes (5622 bytes decrease)
consumer_1   | 2020-03-08T16:49:38.021067852Z Output file size = 132023 bytes (5670 bytes = 4.12% decrease)
consumer_1   | 2020-03-08T16:49:38.021087603Z 
consumer_1   | 2020-03-08T16:49:47.851435281Z Processing sheet #1: /tmp/paperless/paperless-5d25bzsx/convert-0000.pnm -> /tmp/paperless/paperless-5d25bzsx/convert-0000.unpaper.pnm
consumer_1   | 2020-03-08T16:49:47.908611639Z [pgm_pipe @ 0x557f58dc5cc0] Stream #0: not enough frames to estimate rate; consider increasing probesize
consumer_1   | 2020-03-08T16:50:19.721166862Z [image2 @ 0x557f58dc7100] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
consumer_1   | 2020-03-08T16:50:19.750242110Z [image2 @ 0x557f58dc7100] Encoder did not produce proper pts, making some up.
consumer_1   | 2020-03-08T16:50:19.798637922Z OCRing the document
consumer_1   | 2020-03-08T16:50:19.802688493Z Parsing for deu
consumer_1   | 2020-03-08T16:51:14.689207183Z Traceback (most recent call last):
consumer_1   | 2020-03-08T16:51:14.689757186Z   File "/usr/src/paperless/src/manage.py", line 11, in <module>
consumer_1   | 2020-03-08T16:51:14.690066869Z     execute_from_command_line(sys.argv)
consumer_1   | 2020-03-08T16:51:14.690320913Z   File "/usr/lib/python3.8/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
consumer_1   | 2020-03-08T16:51:14.690719311Z     utility.execute()
consumer_1   | 2020-03-08T16:51:14.691370078Z   File "/usr/lib/python3.8/site-packages/django/core/management/__init__.py", line 365, in execute
consumer_1   | 2020-03-08T16:51:14.692019221Z     self.fetch_command(subcommand).run_from_argv(self.argv)
consumer_1   | 2020-03-08T16:51:14.692499671Z   File "/usr/lib/python3.8/site-packages/django/core/management/base.py", line 288, in run_from_argv
consumer_1   | 2020-03-08T16:51:14.693154738Z     self.execute(*args, **cmd_options)
consumer_1   | 2020-03-08T16:51:14.693231678Z   File "/usr/lib/python3.8/site-packages/django/core/management/base.py", line 335, in execute
consumer_1   | 2020-03-08T16:51:14.693259378Z     output = self.handle(*args, **options)
consumer_1   | 2020-03-08T16:51:14.693284317Z   File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 97, in handle
consumer_1   | 2020-03-08T16:51:14.693310005Z     self.loop_inotify(mail_delta)
consumer_1   | 2020-03-08T16:51:14.693334780Z   File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 130, in loop_inotify
consumer_1   | 2020-03-08T16:51:14.693360781Z     self.loop_step(mail_delta)
consumer_1   | 2020-03-08T16:51:14.693385169Z   File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 122, in loop_step
consumer_1   | 2020-03-08T16:51:14.693410870Z     self.file_consumer.consume_new_files()
consumer_1   | 2020-03-08T16:51:14.693436058Z   File "/usr/src/paperless/src/documents/consumer.py", line 117, in consume_new_files
consumer_1   | 2020-03-08T16:51:14.693461259Z     if not self.try_consume_file(file):
consumer_1   | 2020-03-08T16:51:14.693485272Z   File "/usr/lib/python3.8/contextlib.py", line 75, in inner
consumer_1   | 2020-03-08T16:51:14.693509673Z     return func(*args, **kwds)
consumer_1   | 2020-03-08T16:51:14.693533736Z   File "/usr/src/paperless/src/documents/consumer.py", line 158, in try_consume_file
consumer_1   | 2020-03-08T16:51:14.693559274Z     date = parsed_document.get_date()
consumer_1   | 2020-03-08T16:51:14.693583962Z   File "/usr/src/paperless/src/documents/parsers.py", line 136, in get_date
consumer_1   | 2020-03-08T16:51:14.693609163Z     date = __parser(date_string, self.DATE_ORDER)
consumer_1   | 2020-03-08T16:51:14.693634026Z   File "/usr/src/paperless/src/documents/parsers.py", line 87, in __parser
consumer_1   | 2020-03-08T16:51:14.693659027Z     return dateparser.parse(
consumer_1   | 2020-03-08T16:51:14.694983249Z   File "/usr/lib/python3.8/site-packages/dateparser/conf.py", line 83, in wrapper
consumer_1   | 2020-03-08T16:51:14.695143666Z     return f(*args, **kwargs)
consumer_1   | 2020-03-08T16:51:14.695195830Z   File "/usr/lib/python3.8/site-packages/dateparser/__init__.py", line 53, in parse
consumer_1   | 2020-03-08T16:51:14.695276320Z     data = parser.get_date_data(date_string, date_formats)
consumer_1   | 2020-03-08T16:51:14.695370360Z   File "/usr/lib/python3.8/site-packages/dateparser/date.py", line 416, in get_date_data
consumer_1   | 2020-03-08T16:51:14.695421573Z     parsed_date = _DateLocaleParser.parse(
consumer_1   | 2020-03-08T16:51:14.695506551Z   File "/usr/lib/python3.8/site-packages/dateparser/date.py", line 189, in parse
consumer_1   | 2020-03-08T16:51:14.695556077Z     return instance._parse()
consumer_1   | 2020-03-08T16:51:14.695669593Z   File "/usr/lib/python3.8/site-packages/dateparser/date.py", line 199, in _parse
consumer_1   | 2020-03-08T16:51:14.695718531Z     date_obj = parser()
consumer_1   | 2020-03-08T16:51:14.695764495Z   File "/usr/lib/python3.8/site-packages/dateparser/date.py", line 212, in _try_freshness_parser
consumer_1   | 2020-03-08T16:51:14.695812871Z     return freshness_date_parser.get_date_data(self._get_translated_date(), self._settings)
consumer_1   | 2020-03-08T16:51:14.695861085Z   File "/usr/lib/python3.8/site-packages/dateparser/freshness_date_parser.py", line 147, in get_date_data
consumer_1   | 2020-03-08T16:51:14.695909011Z     date, period = self.parse(date_string, settings)
consumer_1   | 2020-03-08T16:51:14.695956388Z   File "/usr/lib/python3.8/site-packages/dateparser/freshness_date_parser.py", line 96, in parse
consumer_1   | 2020-03-08T16:51:14.696004014Z     date, period = self._parse_date(date_string)
consumer_1   | 2020-03-08T16:51:14.696049978Z   File "/usr/lib/python3.8/site-packages/dateparser/freshness_date_parser.py", line 132, in _parse_date
consumer_1   | 2020-03-08T16:51:14.696097129Z     date = self.now - td
consumer_1   | 2020-03-08T16:51:14.696143455Z   File "/usr/lib/python3.8/site-packages/dateutil/relativedelta.py", line 408, in __rsub__
consumer_1   | 2020-03-08T16:51:14.696190619Z     return self.__neg__().__radd__(other)
consumer_1   | 2020-03-08T16:51:14.696236420Z   File "/usr/lib/python3.8/site-packages/dateutil/relativedelta.py", line 405, in __radd__
consumer_1   | 2020-03-08T16:51:14.696284696Z     return self.__add__(other)
consumer_1   | 2020-03-08T16:51:14.696332173Z   File "/usr/lib/python3.8/site-packages/dateutil/relativedelta.py", line 387, in __add__
consumer_1   | 2020-03-08T16:51:14.696380199Z     ret = (other.replace(**repl)
consumer_1   | 2020-03-08T16:51:14.696426288Z ValueError: year -405980 is out of range
```

This happens on e0da952e645490e31dd5e6c003a2d433cdb1f57f.

**Comment by Svarto** [comment]
I have the same error, hope there's a fix for it!

**Comment by languitar** [comment]
@Svarto the referenced pull request would fix the issue.

**Comment by Svarto** [comment]
@languitar thanks a lot! I am waiting for it to be merged, but hasnt happened yet...
