### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'created'

### ISSUE THREAD

**Issue by totti4ever** [the-paperless-project/paperless#633]
Any idea what went wrong and why it's not handled? Interesting fact is that the document is coming from an email and when I drop the pdf into the consumption folder myself

```
paperless-consumer    | Skipping OCR, using Text from PDF
paperless-consumer    | Unable to detect date for document
paperless-consumer    | Traceback (most recent call last):
paperless-consumer    |   File "/usr/src/paperless/src/manage.py", line 11, in <module>
paperless-consumer    |     execute_from_command_line(sys.argv)
paperless-consumer    |   File "/usr/lib/python3.8/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
paperless-consumer    |     utility.execute()
paperless-consumer    |   File "/usr/lib/python3.8/site-packages/django/core/management/__init__.py", line 365, in execute
paperless-consumer    |     self.fetch_command(subcommand).run_from_argv(self.argv)
paperless-consumer    |   File "/usr/lib/python3.8/site-packages/django/core/management/base.py", line 288, in run_from_argv
paperless-consumer    |     self.execute(*args, **cmd_options)
paperless-consumer    |   File "/usr/lib/python3.8/site-packages/django/core/management/base.py", line 335, in execute
paperless-consumer    |     output = self.handle(*args, **options)
paperless-consumer    |   File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 97, in handle
paperless-consumer    |     self.loop_inotify(mail_delta)
paperless-consumer    |   File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 130, in loop_inotify
paperless-consumer    |     self.loop_step(mail_delta)
paperless-consumer    |   File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 122, in loop_step
paperless-consumer    |     self.file_consumer.consume_new_files()
paperless-consumer    |   File "/usr/src/paperless/src/documents/consumer.py", line 117, in consume_new_files
paperless-consumer    |     if not self.try_consume_file(file):
paperless-consumer    |   File "/usr/lib/python3.8/contextlib.py", line 75, in inner
paperless-consumer    |     return func(*args, **kwds)
paperless-consumer    |   File "/usr/src/paperless/src/documents/consumer.py", line 159, in try_consume_file
paperless-consumer    |     document = self._store(
paperless-consumer    |   File "/usr/src/paperless/src/documents/consumer.py", line 218, in _store
paperless-consumer    |     created = file_info.created or date or timezone.make_aware(
paperless-consumer    | AttributeError: 'NoneType' object has no attribute 'created'
```

**Comment by totti4ever** [comment]
nobody faced this issue before?

**Comment by totti4ever** [comment]
This apparently happens when the guesswork fails. Most of my files during migration started with YYYY-MM-DD, which completely killed the consumer :-(

This should be fixable by using `PAPERLESS_FILENAME_PARSE_TRANSFORMS=[{"pattern":"([12]\d{3})-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])", "repl":"\\1\\2\\3"}]`

Nevertheless for ease of use I did `PAPERLESS_FILENAME_PARSE_TRANSFORMS=[{"pattern":"-", "repl":"_"}]` to completely disable it.

I think the guesswork should be stable against finding weird things from it's point of view :-)
