### ISSUE TITLE
consumer not running in Synology Docker

### ISSUE THREAD

**Issue by landcraft** [the-paperless-project/paperless#706]
I used the example files to run docker-compose the 2 containers, and the set up was successful, however the consumer container keep restarting every few seconds, and so far, no documents have been scanned.

running docker logs, I get this:

`Operations to perform:
  Apply all migrations: admin, auth, contenttypes, documents, reminders, sessions
Running migrations:
  No migrations to apply.
Starting document consumer at /consume with inotify
Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.8/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.8/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.8/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.8/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 97, in handle
    self.loop_inotify(mail_delta)
  File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 127, in loop_inotify
    inotify.add_watch(directory, flags.CLOSE_WRITE | flags.MOVED_TO)
  File "/usr/lib/python3.8/site-packages/inotify_simple/inotify_simple.py", line 110, in add_watch
    return _libc_call(_libc.inotify_add_watch, self.fd, path, mask)
  File "/usr/lib/python3.8/site-packages/inotify_simple/inotify_simple.py", line 73, in _libc_call
    raise OSError(errno, os.strerror(errno))
PermissionError: [Errno 13] Permission denied`

Any ideas?

**Comment by landcraft** [comment]
I should add that I've also tried setting it up within Docker in my DSM, and I seem to be facing a similar issue - continuous restarts

**Comment by Tooa** [comment]
Maybe the container does not have permission to access the ./consume directory on your host.  What is the full path of the ./consume directory on your host? How do the permissions look like? Can you try giving it less restrictive permissions? Does it work then?

**Comment by landcraft** [comment]
I set the UID & GID to a user on my Synology that has access rights to the folder. Is there something else I need to do?

**Comment by Selfmade-RuLeZ** [comment]
Got the same error. 
If I'm in the container, I can touch and remove files. 
So I think it has something todo with the document_consumer.py script or something else

**Comment by jonaswinkler** [comment]
Try running the consumer with --no-inotify.

**Comment by jonaswinkler** [comment]
> Edit:
> Running it with this command works. Maybe the docker-entrypoint.sh is wrong
> 
> ```
> python3 /usr/src/paperless/src/manage.py document_consumer
> ```

If you do this, but are running the web server within docker, you will run into trouble, since the consumer will put the consumed documents outside the docker volumes, while the webserver will expect the documents inside the container.

**Comment by Selfmade-RuLeZ** [comment]
Was a permission error, my bad. 
Created the folder before the paperless user had exist. Now it's working.

**Comment by budda85** [comment]
Can you explain what you have done?
I wan't to use it on my Synology also, but the container is stop with no errors in the log.
Which volumes did you map and which environment variables did you use?
I use this [Docker-Image.](https://registry.hub.docker.com/r/thepaperlessproject/paperless)

**Comment by landcraft** [comment]
> Can you explain what you have done?
> I wan't to use it on my Synology also, but the container is stop with no errors in the log.
> Which volumes did you map and which environment variables did you use?
> I use this [Docker-Image.](https://registry.hub.docker.com/r/thepaperlessproject/paperless)

I used [this docker image](https://github.com/jonaswinkler/paperless-ng) and [this guide](https://blog.prutser.net/2020/12/15/manage-your-mail-with-machine-learning-and-paperless-ng/) managed to get it working, with a bit of fiddling (e.g. had to `chmod+x ./manage.py` before `./manage.py createsuperuser`)
